variables:
  SAST_EXCLUDED_PATHS: "frontend/src/assets/private/**"
  TEST_DISABLED: "true"
  DAST_DISABLED: "true"
  SNYK_TOKEN: "7cdf926f-2c8b-47d3-bbe2-d8bfc41561fd"

default:
  image: node:20

include:
  - template: Security/SAST.gitlab-ci.yml

sast:
  stage: test
  artifacts:
    reports:
      sast: gl-sast-report.json
    paths:
      - gl-sast-report.json

test-snyk:
  stage: test
  script:
    # Install npm, snyk, and snyk-to-html
    - npm install
    - npm install -g npm@latest
    # Run snyk help, snyk auth, snyk monitor, snyk test to break build and out report
    - npx snyk --help
    - npx snyk auth $SNYK_TOKEN
    - npx snyk monitor --project-name=$CI_PROJECT_NAME
    - (export SNYK_TEST=$(npm run scan:snyk --json 2>&1 | tee snyk_results.json)) || true
    - npm run report:snyk-to-html -i snyk_results.json -o snyk_results.html && $SNYK_TEST
  artifacts:
    when: always
    paths:
      - snyk_results.json
      - snyk_results.html
    expire_in: 1 week

testa-auditjs:
  stage: test
  script:
    - npm install
    - npm run scan:auditjs --json 2>&1 | tee auditjs_results.json
  # Save report to artifacts
  artifacts:
    when: always
    paths:
      - auditjs_results.json
    expire_in: 1 week

